### Limpieza de los ficheros de censo de locales. 
## Los ficheros analizados son 08-salud-mental.csv. Se carga desde Kaggle 
# Tras analisis se decide no utilizar los datos del dataset por falta de relevancia con el estudio

In [1]:
import altair as alt

# Desactivar vegafusion si quedó activado accidentalmente
alt.data_transformers.enable("default", max_rows=None)

# Renderer compatible con JupyterLab / Anaconda
alt.renderers.enable("mimetype")

RendererRegistry.enable('mimetype')

In [2]:
!pip install reverse_geocoder

Requirement already satisfied: reverse_geocoder in c:\users\raquel\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.11.0 in c:\users\raquel\anaconda3\lib\site-packages (from reverse_geocoder) (2.3.5)
Requirement already satisfied: scipy>=0.17.1 in c:\users\raquel\anaconda3\lib\site-packages (from reverse_geocoder) (1.16.3)

In [3]:
import pandas as pd
import reverse_geocoder as rg
import kagglehub
from kagglehub import KaggleDatasetAdapter
from sklearn.decomposition import PCA
from scipy.cluster import hierarchy
from scipy.cluster.hierarchy import fcluster
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np



pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [7]:
# Carga los datos raw disponibles en Kaggle. En la cuenta del alumno raquelahdo/ruido-datasets

file_path_08 = "08-48130_salud_mental.csv"


df_08 = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "raquelahdo/ruido-datasets",
  file_path_08,
    pandas_kwargs={"encoding": "utf-8-sig", "sep": ";"}
)

In [8]:
df_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 1 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Sexo	Edad	Salud mental	SI o NO_salud mental	periodo	Total  576 non-null    object
dtypes: object(1)
memory usage: 4.6+ KB

In [9]:
df_08.describe()

       Sexo\tEdad\tSalud mental\tSI o NO_salud mental\tperiodo\tTotal
count                                                 576
unique                                                576
top     AMBOS SEXOS\tTOTAL\tPoco interés o alegría por...
freq                                                    1

In [10]:
missing_values_08 = df_08.isnull().sum()
display(missing_values_08)

Sexo\tEdad\tSalud mental\tSI o NO_salud mental\tperiodo\tTotal    0
dtype: int64

In [11]:
df_08.head()

  Sexo\tEdad\tSalud mental\tSI o NO_salud mental\tperiodo\tTotal
0  AMBOS SEXOS\tTOTAL\tPoco interés o alegría por...
1  AMBOS SEXOS\tTOTAL\tPoco interés o alegría por...
2  AMBOS SEXOS\tTOTAL\tPoco interés o alegría por...
3  AMBOS SEXOS\tTOTAL\tPoco interés o alegría por...
4  AMBOS SEXOS\tTOTAL\tPoco interés o alegría por...